//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificacionesCIDI.Secure
{


    public partial class DetNotificacionesGeneral
    {

        protected global::System.Web.UI.HtmlControls.HtmlAnchor btnCerraSession;
         protected global::System.Web.UI.WebControls.GridView gvMasivosAut;
         protected global:: System.Web.UI.WebControls.CheckBox chkSelect;
        /// <summary>
        /// Control DDLEstEnv.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DDLEstEnv;
        protected global::System.Web.UI.WebControls.GridView gvPlantilla;
        /// <summary>
        /// Control txtescripcion.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtescripcion;

    }
}
