//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificacionesCIDI.Secure
{


    public partial class DetNotificacionesGeneral
    {

        protected global::System.Web.UI.HtmlControls.HtmlAnchor btnCerraSession;
         protected global::System.Web.UI.WebControls.GridView gvMasivosAut;
    }
}
